### PR TITLE
add FAQ and info about node alias

### PR DESCRIPTION
**Pull request by derekmiller**

### CODE REVIEW

**Comment by derekmiller** [comment]
@dmnyc go for it 👍

**Comment by dmnyc** [comment]
@derekmiller I made a new version of this with an image and some additional instructions, so you should cancel your PR. Thanks!

https://github.com/PLEBNET/wiki/pull/10

**Comment by phillipalexander** [comment]
YUSSS

**Review by phillipalexander — APPROVED** [review]

**Comment by phjlljp** [comment]
More recent PR obsoleted this one

**Comment by derekmiller** [comment]
Nice!

**Pull request closed without merging**
