### PR TITLE
start with a rough outline

### PR DESCRIPTION
**Pull request by derekmiller**
Obviously need to fill each of these out with links, but here's an idea for the outline.

### CODE REVIEW

**Comment by derekmiller** [comment]
I combined what was in @exfrog branch in to this

**Comment by refazi** [comment]
@derekmiller add me as a reviewer for the pr and let's goooo!!

**Review by refazi — COMMENTED** [review]
lgtm

**Review by refazi — APPROVED** [review]

**Comment by derekmiller** [comment]
Nice! I don't have merge rights but feel free to merge if this is a good starter.

**Comment by refazi** [comment]
> Nice! I don't have merge rights but feel free to merge if this is a good starter.

it seems that i don't have them as well, @phjlljp @dplusplus1024 can you merge?

**Pull request merged**
